### ISSUE TITLE
Js and css paths and maybe add pipes?

### ISSUE THREAD

**Issue by gijsbeijer** [parsnick/laravel-elixir-bowerbundle#2]
Hi,

love your lib! But there's a couple of things i think, would be nice:

- Being able to set different output paths for js and css
- Being able to add a gulp pipe like sass so i could reference .scss files

I'm sorry if this is possible and I just could'nt find out how :p

**Comment by parsnick** [comment]
Thanks for your ideas. I'll add support for different output paths, hopefully today or tomorrow.


> Being able to add a gulp pipe like sass so i could reference .scss files

You might be better off just using this package to get the file list with a custom gulp task:
```js
var Bundle = require('laravel-elixir-bowerbundle/src/Bundle'); // grab the Bundle class
var customBundle = new Bundle(['jquery']); // instantiate with the packages you want
customBundle.files(); // returns [ 'jquery/dist/jquery.js' ]
```

The gulpfile.js might look something like:
```js
// Use elixir as normal
var elixir = require('laravel-elixir');
require('laravel-elixir-bowerbundle');

elixir(function (mix) {
    mix.task('myBower');
});

// Define your custom task
var gulp   = require('gulp');
var filter = require('gulp-filter');
var sass   = require('gulp-sass');
var Bundle = require('laravel-elixir-bowerbundle/src/Bundle');

gulp.task('myBower', function () {
    return gulp.src(new Bundle(['jquery']).files())
        .pipe(filter('*.scss'))
        .pipe(sass())
        // ...
});
```

**Comment by gijsbeijer** [comment]
It's working!

But a lot of packages use .scss files so 'out-of-the-box' support would be nice, or at least clean up the gulpfile a lot ;)

Thanks for the help!

**Comment by parsnick** [comment]
Thanks for confirming that works - I'll improve the API to expose the Bundle class directly, so you won't need to reference a specific file (i.e. the `require('laravel-elixir-bowerbundle/src/Bundle')` bit). And I'll add an example to the readme.

> But a lot of packages use .scss files ...

If it's a common use case then I can certainly add support for sass, but it seems a bit strange. Are there really many Bower packages that only include source sass files and not the compiled css? 

Otherwise, if the package includes both formats, surely the only benefit of consuming the sass over the css is if you want to change some variables used by the sass... and if you do that, you'll need a custom build task anyway, no?

Being able to tap into the gulp pipeline in a generic way, as you originally suggested, could be nice but probably beyond the scope of a small plugin like this. (But if a feature like that gets added to the core Elixir repo then I'd make sure this plugin supports it!)

**Comment by gijsbeijer** [comment]
You're probably right about the sass integration, i've checked and only come across it once and got it working using a sepperate gulp task compiling that file.

Thanks for the help!

**Comment by parsnick** [comment]
No problem!

v2.1.0 adds support for multiple output directories - the output path can now be given as an object like `{ css: 'public/css', js: 'public/js', misc: 'public/assets' }` instead of a single string.

The readme has also been updated, including a section of [using this package with a custom build task](https://github.com/parsnick/laravel-elixir-bowerbundle#use-your-own-build-pipeline).

**Comment by gijsbeijer** [comment]
Sorry  to bother you again :p

Another thing that could be usefull (so the compiled css could be used with the @import in other scss files) is to be able to override the file extension to .scss.

Now you have to use mix.copy(), it wouldn't do the file any harm ;)

**Comment by parsnick** [comment]
It sounds like it's already possible to import plain css from a scss file: https://github.com/sass/libsass/pull/754

(Alternatively, your sass could always import the relevant source sass from bower_components and bypass this plugin completely.)
